### ISSUE TITLE
solidus_active_shipping 1.0.0 not compatible with solidus 1.0.0?

### ISSUE THREAD

**Issue by brchristian** [solidusio-contrib/solidus_active_shipping#37]
It appears that solidus_active_shipping 1.0.0 is not compatible with solidus 1.0.0 -- specifically, that it has a dependency on `solidus > 1.0`. This is surprising and counterintuitive to me. I’m working my way up the upgrade path from Spree now – how would I go about installing a solidus_active_shipping gem compatible with solidus 1.0.0?

**Comment by jhawthorn** [comment]
Hello @brchristian. Good to hear from you.

That probably should be `>=` instead of `>`. However there's no reason you should be using Solidus 1.0.0. If you specify `gem 'solidus', '~> 1.0.0'` in your Gemfile you will get Solidus `1.0.6` which has some major security fixes and some small compatibility fixes. On that subject, it might also be possible for you to upgrade directly to a later minor release (1.4.0 being the latest which supports rails 5). We've tried to have focus on compatibility to make that possible (fingers crossed).

Best of luck.
